/:
  controller: Main
  action: index

/dashboard:
  controller: Main
  action: dashboard
  security: true
  role:
    - 0
    - 1


/contact:
  controller: Main
  action: contact

/login:
  controller: Security
  action: login
  security: false
  role : []

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/{slug}:
  controller:  Main
  action: dashboard
  security: true
  role: []