/:
  controller: Main
  action: index
  security: false
  role: []

/dashboard:
  controller: Main
  action: dashboard
  security: false
  role: []


/contact:
  controller: Main
  action: contact

/login:
  controller: Security
  action: login
  security: false
  role : []

dash/logout:
  controller: Security
  action: logout

/dash/user:
  controller: User
  action: listUser
  security: false
  role:
    - 0

/register:
  controller: Security
  action: register

/{slug}:
  controller:  Main
  action: dashboard
  security: true
  role: []