/:
  controller: Main
  action: index
  security: false
  role: []

/dashboard:
  controller: Main
  action: dashboard
  security: false
  role: []

/login:
  controller: Security
  action: login
  security: false
  role : []

/dash/home :
  controller: Main
  action: dashboard
  security: true
  role: []

/dash/logout:
  controller: Security
  action: logout
  security: true
  role: [ ]

/dash/user:
  controller: User
  action: listUser
  security: true
  role:
    - 0

/dash/categorie:
  controller: Article
  action: listCategorie
  security: true
  role:
    - 0
    - 1

/dash/article:
  controller: Article
  action: listArticle
  security: true
  role:
    - 0
/dash/addarticle:
  controller: Article
  action: newArticle
  security: true
  role:
    - 0

/dash/newarticle:
  controller: Article
  action: newArticles
  security: true
  role:
    - 0
    - 1

/dash/deleteArticle:
  controller: Article
  action: newArticles
  security: true
  role:
    - 0


/dash/edituser:
  controller: User
  action: editUser
  security: true
  role: []

/dash/deleteuser:
  controller: User
  action: deleteUser
  security: true
  role: []

/register:
  controller: Security
  action: register

/{slug}:
  controller:  Main
  action: dashboard
  security: true
  role: []